ekf_filter_node:
  ros__parameters:
    frequency: 10.0
    sensor_timeout: 0.5
    two_d_mode: true
    publish_tf: true
    map_frame: base_link
    odom_frame: base_link
    base_link_frame: base_link
    world_frame: base_link

    # GNSS as position input
    odometry0: /fix
    odometry0_config: [true,  true,  false,
                       false, false, false,
                       false, false, false,
                       false, false, false]
    odometry0_differential: false
    odometry0_relative: false

    # IMU as orientation and acceleration input
    imu0: /imu/data_raw
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true,  true,  true]
    imu0_differential: false
    imu0_relative: false

    use_control: false
    stamped_control: false
    print_diagnostics: true