navsat_transform_node:
  ros__parameters:
    frequency: 10.0
    publish_filtered_gps: true
    use_odometry_yaw: false
    use_local_transform: true
    wait_for_datum: false
    zero_altitude: true
    broadcast_utm_transform: false

    gps_topic: /fix
    imu_topic: /imu/data
    odometry_topic: /odometry/filtered_local